steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - nextjs-app
      - --source
      - .
      - --allow-unauthenticated
      - --set-env-vars
      - _BRANCH_NAME=${_BRANCH_NAME},_COMMIT_SHA=${_COMMIT_SHA}
