name: Deploy Next.js application to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build application
        # run: npx --no-install next build
        run: npm run build

      - name: Check types
        run: npm run typecheck

      - name: Lint JavaScript
        run: npm run lint

      - name: Lint CSS
        run: npm run stylelint

      # - name: Run tests with coverage
      #   run: npm run test:coverage

      # - name: Upload coverage report
      #   uses: codecov/codecov-action@v5
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}

      - name: Cache .next directory
        uses: actions/cache@v4
        with:
          path: .next
          key: ${{ runner.os }}-next-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
              ${{ runner.os }}-next-
